version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Asia/Karachi"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    groups:
      github-actions-minor-patch:
        update-types:
          - "minor"
          - "patch"
